<a href="https://colab.research.google.com/github/jxy-ygjm/EC1B1-Coursework/blob/main/EC1B1_Code_ipynb_Group_55.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EC1B1 Coursework

**Winter Term 2025/2026**

<div style="font-family: system-ui; padding: 20px 30px 20px 20px; background-color: #FFFFFF; border-left: 8px solid #0570b0; border-radius: 8px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);max-width:600px;color:#212121;">

**Coursework Notebook**
- Group 55
    - Xuanyang Ji
    - Felix Kalu
    - Rishi Ganiger
- Date: 28/02/2026

</div>

**Importing libraries**

To run the notebook, we first need to import all the libraries below

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

## Section 1: Importing the Data

In 24/03/2025, International Financial Statistics (IFS) data were discontinued as a single dataset. IMF deleted the "Query" function, so in this Notebook, we download data from different datasets separately.

The raw data are stored on [GitHub](https://github.com/jxy-ygjm/EC1B1-Coursework), allowing easier data import.

We store all the raw data in a dictionary, so we can easily handle procedures like merge

In [2]:
# Raw URL of data
raw_url = (
    "https://raw.githubusercontent.com/jxy-ygjm/EC1B1-Coursework/main/data/raw/"
)

# Specific data name
data_name = [
    "consumer_price", "exchange_rate", "industrial_production",
    "international_reserves"
]

In [3]:
# Create empty dictionary storing data
data = {}

# Read data
for name in data_name:
    data[name] = pd.read_csv(raw_url + name + ".csv")

Now, we try to investigate the dataframes

In [4]:
for value in data.values():
    print(value.columns)

Index(['COUNTRY', 'INDEX_TYPE', 'COICOP_1999', 'TYPE_OF_TRANSFORMATION',
       'FREQUENCY', 'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'INDICATOR', 'TYPE_OF_TRANSFORMATION', 'FREQUENCY',
       'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'PRODUCTION_INDEX', 'TYPE_OF_TRANSFORMATION', 'FREQUENCY',
       'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
Index(['COUNTRY', 'INDICATOR', 'UNIT', 'FREQUENCY', 'TIME_PERIOD', 'OBS_VALUE',
       'SCALE'],
      dtype='object')

We can see that only the `TIME_PERIOD` and `OBS_VALUE` are useful to us.

We now try to create a single dataframe for Spain and US

In [5]:
# Set a list for clean Spain data
spain_cleaned = []

for name, df in data.items():
    temp = df[df["COUNTRY"] == "Spain"][["TIME_PERIOD", "OBS_VALUE"]].copy()
    temp = temp.rename(columns={"OBS_VALUE": name})
    temp = temp.set_index("TIME_PERIOD")
    spain_cleaned.append(temp)

df_spain = pd.concat(spain_cleaned, axis=1)

In [6]:
# Investigate the dataframe
df_spain.head()

,consumer_price,exchange_rate,industrial_production,international_reserves
TIME_PERIOD,,,,
1959-M12,2.525752,60.0,NaN,200.14101
1960-M01,2.505928,60.0,NaN,233.26019
1960-M02,2.503895,60.0,NaN,253.21561
1960-M03,2.500846,60.0,NaN,299.28248
1960-M04,2.502879,60.0,NaN,326.28248

In [7]:
# Set a list for clean US data
us_cleaned = []

for name, df in data.items():
    temp = (
        df[df["COUNTRY"] == "United States"]
        [["TIME_PERIOD", "OBS_VALUE"]]
        .copy()
    )
    temp = temp.rename(columns={"OBS_VALUE": name})
    temp = temp.set_index("TIME_PERIOD")
    us_cleaned.append(temp)

df_us = pd.concat(us_cleaned, axis=1)

In [8]:
# Investigate the dataframe
df_us.head()

,consumer_price,exchange_rate,industrial_production,international_reserves
TIME_PERIOD,,,,
1959-M12,13.482806,NaN,NaN,21543.4138
1960-M01,13.436946,NaN,NaN,21539.3167
1960-M02,13.482806,NaN,NaN,21445.6179
1960-M03,13.482806,NaN,NaN,21411.2592
1960-M04,13.528666,NaN,NaN,21344.4744

Remember no data for `exchange_rate` and `industrial_production` so drop them

In [9]:
df_us = df_us.drop(columns=["exchange_rate", "industrial_production"])

As `consumer_price`, `exchange_rate` and `industrial_production` are indices or have direct meaning, we do not need to know their scale, but for international_reserves, as its nominal measure, we need to know its scale

In [10]:
data["international_reserves"]["SCALE"].head()

0    Millions
1    Millions
2    Millions
3    Millions
4    Millions
Name: SCALE, dtype: object

Can see all the data are in Millions scale, we can rename the column to highlight this

In [11]:
df_spain = df_spain.rename(
    columns={"international_reserves": "international_reserves (M)"}
)
df_us = df_us.rename(
    columns={"international_reserves": "international_reserves (M)"}
)

In [12]:
df_spain.head()

,consumer_price,exchange_rate,industrial_production,international_reserves (M)
TIME_PERIOD,,,,
1959-M12,2.525752,60.0,NaN,200.14101
1960-M01,2.505928,60.0,NaN,233.26019
1960-M02,2.503895,60.0,NaN,253.21561
1960-M03,2.500846,60.0,NaN,299.28248
1960-M04,2.502879,60.0,NaN,326.28248

## Section 2: Cleaning the Data

### The monthly growth in the nominal exchange rate

In [13]:
# Set the name of the country
df_spain["COUNTRY"] = "Spain"
df_us["COUNTRY"] = "US"

# Combine datasets
df = pd.concat([df_spain, df_us], axis=0).reset_index()

In [14]:
# See dataframe
df

,TIME_PERIOD,consumer_price,exchange_rate,industrial_production,international_reserves (M),COUNTRY
0,1959-M12,2.525752,60.0,NaN,200.141010,Spain
1,1960-M01,2.505928,60.0,NaN,233.260190,Spain
2,1960-M02,2.503895,60.0,NaN,253.215610,Spain
3,1960-M03,2.500846,60.0,NaN,299.282480,Spain
4,1960-M04,2.502879,60.0,NaN,326.282480,Spain
...,...,...,...,...,...,...
741,1990-M08,60.351608,NaN,NaN,169458.603357,US
742,1990-M09,60.856066,NaN,NaN,175533.733633,US
743,1990-M10,61.222946,NaN,NaN,170874.784032,US
744,1990-M11,61.360525,NaN,NaN,172797.695574,US
745,1990-M12,61.360525,NaN,NaN,173093.564608,US

The IMF provides the nominal exchange rate as National Currency per US Dollar (period average)

This means Eₜ is defined as domestic currency per 1 USD, i.e. Spain currency / USD

Therefore, a higher Eₜ means a depreciation of Spain currency and an appreciation of USD

In [15]:
# Construct nominal exchange rate growth for Spain
df["nominal_exchange_rate_growth"] = (
    df.groupby("COUNTRY")["exchange_rate"]
      .transform(lambda x: np.log(x) - np.log(x.shift(1)))
)

There is no exchange rate data for US so `groupby` will not result error

### The monthly growth in the real exchange rate

As our nominal exchange rate is in the format of Spain currency / USD, so to calculate real exchange rate, we can use

ϵ = (E × Pᵤ) / Pₛ

where Pᵤ is the price level in US, and Pₛ is the price level in Spain

In [16]:
# Get US consumer price out for easy calculation of real exchange rate
us_consumer_price = (
    df[df["COUNTRY"] == "US"]
    [["TIME_PERIOD", "consumer_price"]]
    .rename(columns={"consumer_price": "consumer_price_us"})
)

# Merge dataframe
df = df.merge(us_consumer_price, on="TIME_PERIOD", how="left")

# Calculate real exchange rate for Spain
df["real_exchange_rate"] = (
    df["exchange_rate"] * df["consumer_price_us"] / df["consumer_price"]
)

# Calculate real exchange rate growth for Spain
df["real_exchange_rate_growth"] = (
    df.groupby("COUNTRY")["real_exchange_rate"]
      .transform(lambda x: np.log(x) - np.log(x.shift(1)))
)

# Drop real_exchange_rate and consumer_price_us that is not ask
df = df.drop(columns=["real_exchange_rate", "consumer_price_us"])

There is no exchange rate data for US so calculate real exchange rate and `groupby` will not result error

### An index of the real exchange rate

In [17]:
# Collect Spain data
spain = df[df["COUNTRY"] == "Spain"].copy()

# Calculate cumulative log level
spain["real_exchange_rate_log_level"] = (spain["real_exchange_rate_growth"]
                                     .fillna(0)
                                     .cumsum()
)

# Calculate cumulative level
spain["real_exchange_rate_level"] = np.exp(
    spain["real_exchange_rate_log_level"]
)

# Set index
spain["real_exchange_rate_index"] = (
    spain["real_exchange_rate_level"] /
    spain.loc[
        spain["TIME_PERIOD"] == "1990-M12", "real_exchange_rate_level"
    ].iloc[0]
)

# Merge
df = df.merge(
    spain[["COUNTRY", "TIME_PERIOD", "real_exchange_rate_index"]],
    on=["COUNTRY", "TIME_PERIOD"],
    how="left"
)

### The monthly inflation rate

In [18]:
# Construct monthly inflation rate for both Spain and the US
df["inflation"] = (
    df.groupby("COUNTRY")["consumer_price"]
      .transform(lambda x: np.log(x) - np.log(x.shift(1)))
)

### The monthly growth in industrial production

In [19]:
# Construct industrial production growth for Spain
df["industrial_production_growth_month"] = (
    df.groupby("COUNTRY")["industrial_production"]
      .transform(lambda x: np.log(x) - np.log(x.shift(1)))
)

### The growth in industrial production versus 12 months ago

In [20]:
# Construct yearly industrial production growth for Spain
df["industrial_production_growth_year"] = (
    df.groupby("COUNTRY")["industrial_production"]
      .transform(lambda x: np.log(x) - np.log(x.shift(12)))
)

### An index of the value of international reserves

In [21]:
# Collect Spain data
spain = df[df["COUNTRY"] == "Spain"].copy()

# Calculate index
spain["international_reserves_index"] = (
    spain["international_reserves (M)"] /
    spain.loc[
        spain["TIME_PERIOD"] == "1960-M01", "international_reserves (M)"
    ].iloc[0] * 100
)

In [22]:
# Collect US data
us = df[df["COUNTRY"] == "US"].copy()

# Calculate index
us["international_reserves_index"] = (
    us["international_reserves (M)"] /
    us.loc[
        us["TIME_PERIOD"] == "1960-M01", "international_reserves (M)"
    ].iloc[0] * 100
)

In [23]:
# Concat together
international_reserves_index = pd.concat(
    [spain[["TIME_PERIOD","COUNTRY", "international_reserves_index"]],
     us[["TIME_PERIOD","COUNTRY", "international_reserves_index"]]],
    axis=0
)

# Merge
df = df.merge(
    international_reserves_index,
    on=["COUNTRY", "TIME_PERIOD"],
    how="left"
)

In [24]:
# Format date
df["TIME_PERIOD"] = df["TIME_PERIOD"].apply(
    lambda x: datetime.strptime(x, "%Y-M%m")
)

In [25]:
# Show the full dataset
pd.set_option("display.max_rows", None)
df

,TIME_PERIOD,consumer_price,exchange_rate,industrial_production,international_reserves (M),COUNTRY,nominal_exchange_rate_growth,real_exchange_rate_growth,real_exchange_rate_index,inflation,industrial_production_growth_month,industrial_production_growth_year,international_reserves_index
0,1959-12-01,2.525752,60.000000,NaN,200.141010,Spain,NaN,NaN,2.561868,NaN,NaN,NaN,85.801615
1,1960-01-01,2.505928,60.000000,NaN,233.260190,Spain,0.000000,0.004473,2.573352,-0.007880,NaN,NaN,100.000000
2,1960-02-01,2.503895,60.000000,NaN,253.215610,Spain,0.000000,0.004219,2.584231,-0.000812,NaN,NaN,108.555005
3,1960-03-01,2.500846,60.000000,NaN,299.282480,Spain,0.000000,0.001218,2.587382,-0.001218,NaN,NaN,128.304140
4,1960-04-01,2.502879,60.000000,NaN,326.282480,Spain,0.000000,0.002583,2.594074,0.000813,NaN,NaN,139.879197
5,1960-05-01,2.495255,60.000000,NaN,360.215610,Spain,0.000000,0.003051,2.602000,-0.003051,NaN,NaN,154.426527
6,1960-06-01,2.493221,60.000000,NaN,406.215610,Spain,0.000000,0.004200,2.612950,-0.000815,NaN,NaN,174.146994
7,1960-07-01,2.492204,60.000000,NaN,427.304770,Spain,0.000000,0.000408,2.614016,-0.000408,NaN,NaN,183.188040
8,1960-08-01,2.497288,60.000000,NaN,455.392240,Spain,0.000000,-0.002038,2.608695,0.002038,NaN,NaN,195.229302
9,1960-09-01,2.512536,60.000000,NaN,479.644000,Spain,0.000000,-0.006087,2.592863,0.006087,NaN,NaN,205.626172
10,1960-10-01,2.519145,60.000000,NaN,531.066290,Spain,0.000000,0.004107,2.603534,0.002627,NaN,NaN,227.671207
11,1960-11-01,2.522194,60.000000,NaN,523.788680,Spain,0.000000,-0.001210,2.600387,0.001210,NaN,NaN,224.551253
12,1960-12-01,2.541002,60.000000,NaN,544.061600,Spain,0.000000,-0.007429,2.581139,0.007429,NaN,NaN,233.242372
13,1961-01-01,2.551676,60.000000,18.687510,537.944000,Spain,0.000000,-0.004192,2.570342,0.004192,NaN,NaN,230.619721
14,1961-02-01,2.530835,60.000000,18.253463,565.463560,Spain,0.000000,0.008201,2.591508,-0.008201,-0.023501,NaN,242.417517
15,1961-03-01,2.519653,60.000000,18.429428,562.072130,Spain,0.000000,0.004428,2.603009,-0.004428,0.009594,NaN,240.963591
16,1961-04-01,2.526261,60.000000,18.617124,593.963560,Spain,0.000000,-0.002619,2.596200,0.002619,0.010133,NaN,254.635632
17,1961-05-01,2.519653,60.000000,19.590799,643.846420,Spain,0.000000,0.002619,2.603009,-0.002619,0.050978,NaN,276.020705
18,1961-06-01,2.505928,60.000000,18.452890,683.996000,Spain,0.000000,0.005462,2.617266,-0.005462,-0.059839,NaN,293.233063
19,1961-07-01,2.505928,60.000000,17.619988,717.460940,Spain,0.000000,0.006689,2.634832,0.000000,-0.046187,NaN,307.579677
20,1961-08-01,2.509995,60.000000,17.690374,774.987830,Spain,0.000000,-0.004961,2.621794,0.001622,0.003987,NaN,332.241790
21,1961-09-01,2.512028,60.000000,19.649454,796.987830,Spain,0.000000,0.002529,2.628433,0.000810,0.105029,NaN,341.673318
22,1961-10-01,2.521686,60.000000,20.212543,827.173600,Spain,0.000000,-0.003837,2.618366,0.003837,0.028254,NaN,354.614133
23,1961-11-01,2.560825,60.000000,21.843154,852.895640,Spain,0.000000,-0.015402,2.578348,0.015402,0.077584,NaN,365.641321
24,1961-12-01,2.565400,60.000000,23.450303,887.873550,Spain,0.000000,-0.001785,2.573750,0.001785,0.070996,NaN,380.636554
25,1962-01-01,2.560825,60.000000,22.089505,913.500360,Spain,0.000000,0.001785,2.578348,-0.001785,-0.059781,0.167247,391.622917
26,1962-02-01,2.572516,60.000000,21.010252,935.775560,Spain,0.000000,-0.001227,2.575186,0.004555,-0.050092,0.140656,401.172425
27,1962-03-01,2.594881,60.000000,22.394512,959.492720,Spain,0.000000,-0.008656,2.552991,0.008656,0.063805,0.194867,411.340109
28,1962-04-01,2.631479,60.000000,20.587935,978.362220,Spain,0.000000,-0.010689,2.525848,0.014005,-0.084111,0.100623,419.429573
29,1962-05-01,2.665027,60.000000,21.362182,989.218840,Spain,0.000000,-0.012668,2.494052,0.012668,0.036917,0.086562,424.083870
30,1962-06-01,2.678751,60.000000,20.834286,1005.392330,Spain,0.000000,-0.005136,2.481274,0.005136,-0.025022,0.121379,431.017539
31,1962-07-01,2.678751,60.000000,19.907536,1033.264590,Spain,0.000000,0.003306,2.489490,0.000000,-0.045502,0.122064,442.966539
32,1962-08-01,2.672143,60.000000,18.980786,1028.299190,Spain,0.000000,0.002470,2.495647,-0.002470,-0.047671,0.070407,440.837843
33,1962-09-01,2.688409,60.000000,20.200811,1048.965840,Spain,0.000000,-0.002774,2.488734,0.006069,0.062296,0.027673,449.697756
34,1962-10-01,2.714332,60.000000,21.772768,1047.393190,Spain,0.000000,-0.009596,2.464965,0.009596,0.074937,0.074357,449.023552
35,1962-11-01,2.783970,60.000000,23.379917,1047.508880,Spain,0.000000,-0.025332,2.403307,0.025332,0.071217,0.067990,449.073149
36,1962-12-01,2.819551,60.000000,24.212819,1045.887990,Spain,0.000000,-0.012700,2.372979,0.012700,0.035005,0.031999,448.378264
37,1963-01-01,2.826159,60.000000,24.224550,1062.846790,Spain,0.000000,-0.002341,2.367430,0.002341,0.000484,0.092264,455.648600
38,1963-02-01,2.848524,60.000000,22.875483,1063.275570,Spain,0.000000,-0.007882,2.348842,0.007882,-0.057301,0.085055,455.832420
39,1963-03-01,2.903929,60.000000,23.344724,1039.222330,Spain,0.000000,-0.015980,2.311607,0.019264,0.020305,0.041555,445.520657
40,1963-04-01,2.901896,60.000000,22.816828,1039.689360,Spain,0.000000,0.000700,2.313227,-0.000700,-0.022873,0.102793,445.720875
41,1963-05-01,2.918161,60.000000,23.661462,1036.000790,Spain,0.000000,-0.005589,2.300333,0.005589,0.036349,0.102225,444.139564
42,1963-06-01,2.864281,60.000000,22.547015,1032.803120,Spain,0.000000,0.021910,2.351289,-0.018636,-0.048245,0.079003,442.768704
43,1963-07-01,2.894780,60.000000,21.620265,1055.640000,Spain,0.000000,-0.007329,2.334119,0.010592,-0.041972,0.082533,452.559007
44,1963-08-01,2.924769,60.000000,20.904673,1107.698670,Spain,0.000000,-0.010306,2.310186,0.010306,-0.033658,0.096546,474.876862
45,1963-09-01,2.918161,60.000000,22.324126,1120.358420,Spain,0.000000,0.002262,2.315417,-0.002262,0.065695,0.099945,480.304170
46,1963-10-01,2.926294,60.000000,24.306667,1108.785810,Spain,0.000000,0.000469,2.316503,0.002783,0.085083,0.110091,475.342925
47,1963-11-01,2.962892,60.000000,24.635136,1107.294680,Spain,0.000000,-0.012429,2.287890,0.012429,0.013423,0.052296,474.703669
48,1963-12-01,2.974074,60.000000,25.761314,1148.505160,Spain,0.000000,-0.000525,2.286688,0.003767,0.044700,0.061992,492.370841
49,1964-01-01,2.969500,60.000000,26.852298,1184.014040,Spain,0.000000,0.001539,2.290210,-0.001539,0.041478,0.102985,507.593705
50,1964-02-01,2.971533,60.000000,26.664602,1188.119280,Spain,0.000000,-0.000684,2.288643,0.000684,-0.007014,0.153271,509.353645
51,1964-03-01,2.980682,60.000000,24.940142,1211.724520,Spain,0.000000,-0.003074,2.281618,0.003074,-0.066858,0.066108,519.473349
52,1964-04-01,2.991865,60.000000,26.160168,1215.619280,Spain,0.000000,-0.003745,2.273090,0.003745,0.047759,0.136740,521.143055
53,1964-05-01,2.999489,60.000000,26.066320,1222.505160,Spain,0.000000,-0.002545,2.267313,0.002545,-0.003594,0.096796,524.095072
54,1964-06-01,3.039645,60.000000,26.007665,1266.504720,Spain,0.000000,-0.010068,2.244600,0.013299,-0.002253,0.142789,542.957939
55,1964-07-01,3.105217,60.000000,25.479769,1316.328880,Spain,0.000000,-0.018122,2.204289,0.021343,-0.020507,0.164254,564.317846
56,1964-08-01,3.154013,60.000000,22.687787,1396.127280,Spain,0.000000,-0.018813,2.163209,0.015592,-0.116058,0.081854,598.527884
57,1964-09-01,3.185019,60.000000,25.784776,1461.410600,Spain,0.000000,-0.006562,2.149060,0.009783,0.127957,0.144116,626.515223
58,1964-10-01,3.237375,60.000000,26.910953,1487.767440,Spain,0.000000,-0.016305,2.114305,0.016305,0.042749,0.101783,637.814554
59,1964-11-01,3.312095,60.000000,28.224827,1491.246000,Spain,0.000000,-0.019608,2.073252,0.022818,0.047669,0.136028,639.305833
60,1964-12-01,3.350726,60.000000,29.233695,1515.235680,Spain,0.000000,-0.011596,2.049349,0.011596,0.035120,0.126448,649.590348
61,1965-01-01,3.383766,60.000000,28.048862,1558.396230,Spain,0.000000,-0.009812,2.029338,0.009812,-0.041374,0.043597,668.093527
62,1965-02-01,3.441712,60.000000,29.480046,1541.908820,Spain,0.000000,-0.016980,1.995172,0.016980,0.049766,0.100377,661.025278
63,1965-03-01,3.468652,60.000000,31.040271,1512.153350,Spain,0.000000,-0.004597,1.986021,0.007797,0.051572,0.218807,648.268935
64,1965-04-01,3.494067,60.000000,30.207369,1471.030660,Spain,0.000000,-0.004111,1.977874,0.007300,-0.027200,0.143848,630.639399
65,1965-05-01,3.508300,60.000000,31.157581,1446.248600,Spain,0.000000,-0.004065,1.969850,0.004065,0.030972,0.178414,620.015186
66,1965-06-01,3.492543,60.000000,30.078328,1454.248600,Spain,0.000000,0.010851,1.991340,-0.004501,-0.035253,0.145414,623.444832
67,1965-07-01,3.497117,60.000000,30.805651,1468.949310,Spain,0.000000,-0.001309,1.988736,0.001309,0.023893,0.189813,629.747112
68,1965-08-01,3.514908,60.000000,25.831700,1505.897520,Spain,0.000000,-0.005074,1.978670,0.005074,-0.176096,0.129776,645.587025
69,1965-09-01,3.548456,60.000000,30.746996,1527.054820,Spain,0.000000,-0.009499,1.959963,0.009499,0.174190,0.176008,654.657282
70,1965-10-01,3.567263,60.000000,31.638553,1479.897520,Spain,0.000000,-0.002126,1.955799,0.005286,0.028584,0.161843,634.440673
71,1965-11-01,3.644016,60.000000,32.659152,1447.666060,Spain,0.000000,-0.021288,1.914605,0.021288,0.031749,0.145923,620.622859
72,1965-12-01,3.664857,60.000000,33.011082,1411.897520,Spain,0.000000,-0.002553,1.909723,0.005703,0.010718,0.121521,605.288678
73,1966-01-01,3.658249,60.000000,32.893772,1381.054820,Spain,0.000000,0.001805,1.913172,-0.001805,-0.003560,0.159335,592.066233
74,1966-02-01,3.655199,60.000000,33.550709,1331.054820,Spain,0.000000,0.007104,1.926811,-0.000834,0.019775,0.129344,570.630942
75,1966-03-01,3.655199,60.000000,36.483463,1268.565100,Spain,0.000000,0.003120,1.932832,0.000000,0.083801,0.161574,543.841236
76,1966-04-01,3.690272,60.000000,34.805928,1225.116420,Spain,0.000000,-0.003338,1.926390,0.009550,-0.047071,0.141702,525.214534
77,1966-05-01,3.744152,60.000000,35.591906,1224.340760,Spain,0.000000,-0.014495,1.898669,0.014495,0.022331,0.133061,524.882004
78,1966-06-01,3.751268,60.000000,35.228244,1197.013780,Spain,0.000000,0.001192,1.900934,0.001899,-0.010270,0.158043,513.166769
79,1966-07-01,3.749235,60.000000,33.128392,1207.238120,Spain,0.000000,0.003624,1.907835,-0.000542,-0.061457,0.072693,517.550003
80,1966-08-01,3.755843,60.000000,29.421391,1253.462460,Spain,0.000000,0.004374,1.916199,0.001761,-0.118669,0.130120,537.366646
81,1966-09-01,3.744152,60.000000,35.650561,1281.568030,Spain,0.000000,0.003118,1.922182,-0.003118,0.192043,0.147973,549.415668
82,1966-10-01,3.767025,60.000000,36.600773,1250.670550,Spain,0.000000,0.000007,1.922196,0.006090,0.026304,0.145693,536.169738
83,1966-11-01,3.832596,60.000000,36.600773,1222.119290,Spain,0.000000,-0.017257,1.889309,0.017257,0.000000,0.113944,523.929647
84,1966-12-01,3.857503,60.000000,37.973302,1210.578030,Spain,0.000000,-0.006478,1.877110,0.006478,0.036814,0.140040,518.981842
85,1967-01-01,3.859536,60.000000,35.885181,1165.758660,Spain,0.000000,-0.000527,1.876122,0.000527,-0.056559,0.087041,499.767517
86,1967-02-01,3.889527,60.000000,34.629963,1106.862100,Spain,0.000000,-0.007741,1.861655,0.007741,-0.035605,0.031661,474.518219
87,1967-03-01,3.905792,60.000000,36.847125,1041.534520,Spain,0.000000,-0.001138,1.859538,0.004173,0.062058,0.009918,446.511906
88,1967-04-01,3.960180,60.000000,37.562717,992.758660,Spain,0.000000,-0.010803,1.839557,0.013829,0.019234,0.076224,425.601411
89,1967-05-01,3.973904,60.000000,37.023090,986.534520,Spain,0.000000,-0.000443,1.838742,0.003460,-0.014470,0.039424,422.933086
90,1967-06-01,3.939340,60.000000,37.621372,993.758660,Spain,0.000000,0.011743,1.860463,-0.008736,0.016031,0.065724,426.030117
91,1967-07-01,3.941881,60.000000,35.169589,1069.758660,Spain,0.000000,0.002354,1.864847,0.000645,-0.067391,0.059791,458.611759
92,1967-08-01,3.999319,60.000000,30.078328,1121.864230,Spain,0.000000,-0.011477,1.843567,0.014466,-0.156377,0.022083,480.949720
93,1967-09-01,4.010502,60.000000,35.521520,1111.864230,Spain,0.000000,0.000188,1.843914,0.002792,0.166334,-0.003626,476.662662
94,1967-10-01,4.026768,60.000000,36.002492,1073.864230,Spain,0.000000,-0.001076,1.841931,0.004048,0.013449,-0.016481,460.371841
95,1967-11-01,4.110637,70.000000,37.199055,1036.088400,Spain,0.154151,0.136500,2.111322,0.020614,0.032695,0.016214,444.177123
96,1967-12-01,4.110637,70.000000,37.257710,1053.098400,Spain,0.000000,0.002954,2.117569,0.000000,0.001576,-0.019024,451.469408
97,1968-01-01,4.122329,70.000000,37.562717,1096.088400,Spain,0.000000,0.003042,2.124020,0.002840,0.008153,0.045688,469.899471
98,1968-02-01,4.122329,70.000000,38.219654,1069.088400,Spain,0.000000,0.002928,2.130249,0.000000,0.017338,0.098631,458.324414
99,1968-03-01,4.164517,70.000000,38.876591,1168.326000,Spain,0.000000,-0.007262,2.114835,0.010182,0.017042,0.053615,500.868151
100,1968-04-01,4.201115,70.000000,38.160999,1183.632000,Spain,0.000000,-0.005838,2.102523,0.008750,-0.018578,0.015802,507.429922
101,1968-05-01,4.187391,70.000000,40.131810,1211.529000,Spain,0.000000,0.006175,2.115546,-0.003272,0.050355,0.080628,519.389528
102,1968-06-01,4.199082,70.000000,38.817936,1185.988000,Spain,0.000000,0.002992,2.121886,0.002788,-0.033287,0.031310,508.439953
103,1968-07-01,4.164517,70.000000,37.797337,1172.027000,Spain,0.000000,0.014013,2.151829,-0.008266,-0.026644,0.072057,502.454791
104,1968-08-01,4.167059,70.000000,31.755863,1248.326000,Spain,0.000000,0.002251,2.156678,0.000610,-0.174161,0.054272,535.164616
105,1968-09-01,4.160451,70.000000,38.641970,1268.842000,Spain,0.000000,0.004440,2.166275,-0.001587,0.196262,0.084200,543.959944
106,1968-10-01,4.173667,70.000000,41.211063,1255.507000,Spain,0.000000,0.002510,2.171720,0.003172,0.064368,0.135119,538.243152
107,1968-11-01,4.201115,70.000000,41.750690,1240.566550,Spain,0.000000,-0.003726,2.163643,0.006555,0.013009,0.115433,531.838095
108,1968-12-01,4.229072,70.000000,43.005909,1303.543700,Spain,0.000000,-0.003812,2.155412,0.006633,0.029622,0.143479,558.836765
109,1969-01-01,4.219414,70.000000,43.604191,1296.884420,Spain,0.000000,0.005099,2.166431,-0.002286,0.013816,0.149141,555.981893
110,1969-02-01,4.193999,70.000000,42.524937,1309.472100,Spain,0.000000,0.011644,2.191804,-0.006042,-0.025063,0.106741,561.378305
111,1969-03-01,4.219414,70.000000,46.947531,1272.956700,Spain,0.000000,0.002303,2.196858,0.006042,0.098940,0.188638,545.723940
112,1969-04-01,4.269228,70.000000,45.750967,1289.652800,Spain,0.000000,-0.006212,2.183254,0.011737,-0.025818,0.181399,552.881655
113,1969-05-01,4.269228,70.000000,46.888875,1280.992840,Spain,0.000000,0.002751,2.189268,0.000000,0.024568,0.155611,549.169080
114,1969-06-01,4.219414,70.000000,45.809622,1256.837600,Spain,0.000000,0.017216,2.227286,-0.011737,-0.023286,0.165612,538.813588
115,1969-07-01,4.252453,70.000000,43.780156,1330.222140,Spain,0.000000,-0.002350,2.222057,0.007800,-0.045314,0.146942,570.273967
116,1969-08-01,4.265670,70.000000,37.023090,1293.333780,Spain,0.000000,0.002317,2.227211,0.003103,-0.167639,0.153464,554.459713
117,1969-09-01,4.273802,70.000000,45.809622,1233.297640,Spain,0.000000,0.000794,2.228982,0.001905,0.212952,0.170155,528.721871
118,1969-10-01,4.290068,70.000000,48.144094,1215.444250,Spain,0.000000,0.001578,2.232501,0.003799,0.049704,0.155492,521.068019
119,1969-11-01,4.328191,70.000000,46.407904,1124.388800,Spain,0.000000,-0.003499,2.224702,0.008847,-0.036729,0.105754,482.032018
120,1969-12-01,4.373938,70.000000,47.006186,1285.926800,Spain,0.000000,-0.005195,2.213175,0.010514,0.012809,0.088942,551.284298
121,1970-01-01,4.394778,70.000000,47.968129,1350.220910,Spain,0.000000,-0.002104,2.208523,0.004753,0.020258,0.095384,578.847556
122,1970-02-01,4.378005,70.000000,48.390446,1368.893180,Spain,0.000000,0.009101,2.228714,-0.003824,0.008766,0.129212,586.852467
123,1970-03-01,4.411552,70.000000,47.721778,1370.787700,Spain,0.000000,-0.002384,2.223407,0.007633,-0.013915,0.016357,587.664659
124,1970-04-01,4.435951,70.000000,51.440510,1363.092650,Spain,0.000000,0.002307,2.228543,0.005515,0.075038,0.117213,584.365746
125,1970-05-01,4.406978,70.000000,48.988728,1367.139050,Spain,0.000000,0.009147,2.249020,-0.006553,-0.048836,0.043810,586.100461
126,1970-06-01,4.423752,70.000000,49.645664,1401.035410,Spain,0.000000,0.001369,2.252101,0.003799,0.013321,0.080417,600.632028
127,1970-07-01,4.507113,70.000000,48.390446,1601.777700,Spain,0.000000,-0.013527,2.221842,0.018669,-0.025609,0.100122,686.691415
128,1970-08-01,4.578275,70.000000,38.512929,1515.370200,Spain,0.000000,-0.015665,2.187307,0.015665,-0.228308,0.039452,649.648018
129,1970-09-01,4.599115,70.000000,47.909474,1612.531600,Spain,0.000000,0.000573,2.188562,0.004542,0.218319,0.044819,691.301675
130,1970-10-01,4.644863,70.000000,49.645664,1701.510250,Spain,0.000000,-0.004809,2.178062,0.009898,0.035598,0.030713,729.447339
131,1970-11-01,4.657062,70.000000,51.194159,1771.938260,Spain,0.000000,0.002440,2.183384,0.002623,0.030714,0.098156,759.640237
132,1970-12-01,4.670278,70.000000,49.223348,1851.302470,Spain,0.000000,0.002204,2.188201,0.002834,-0.039257,0.046089,793.664135
133,1971-01-01,4.719584,70.000000,49.282003,2025.753700,Spain,0.000000,-0.010502,2.165341,0.010502,0.001191,0.027022,868.452392
134,1971-02-01,4.716025,70.000000,50.114905,2063.429200,Spain,0.000000,0.003264,2.172420,-0.000754,0.016760,0.035016,884.604098
135,1971-03-01,4.765839,70.000000,53.164970,2132.425580,Spain,0.000000,-0.008004,2.155101,0.010507,0.059081,0.108012,914.183247
136,1971-04-01,4.816161,70.000000,51.616475,2199.609800,Spain,0.000000,-0.008007,2.137915,0.010504,-0.029559,0.003415,942.985513
137,1971-05-01,4.845642,70.000000,52.332067,2323.836560,Spain,0.000000,-0.001127,2.135505,0.006103,0.013768,0.066019,996.242248
138,1971-06-01,4.865974,70.000000,53.235356,2430.303400,Spain,0.000000,0.003229,2.142413,0.004187,0.017113,0.069812,1041.885201
139,1971-07-01,4.865974,70.000000,52.214757,2685.041600,Spain,0.000000,0.002460,2.147690,0.000000,-0.019358,0.076063,1151.092949
140,1971-08-01,4.874615,69.504000,41.692035,2905.132100,Spain,-0.007111,-0.006431,2.133922,0.001774,-0.225055,0.079316,1245.447026
141,1971-09-01,4.932562,69.278000,51.675130,3055.888400,Spain,-0.003257,-0.015074,2.101996,0.011817,0.214667,0.075663,1310.077129
142,1971-10-01,4.986950,68.889000,52.930349,3158.187560,Spain,-0.005631,-0.014149,2.072465,0.010966,0.024000,0.064066,1353.933374
143,1971-11-01,5.054554,68.535000,54.666540,3258.132400,Spain,-0.005152,-0.018617,2.034238,0.013465,0.032275,0.065626,1396.780308
144,1971-12-01,5.120634,67.418000,54.431919,3347.891154,Spain,-0.016433,-0.024543,1.984919,0.012989,-0.004301,0.100583,1435.260408
145,1972-01-01,5.124700,65.908000,56.402730,3521.453821,Spain,-0.022652,-0.023446,1.938922,0.000794,0.035567,0.134959,1509.667732
146,1972-02-01,5.120634,65.908000,58.009880,3637.399521,Spain,0.000000,0.005648,1.949905,-0.000794,0.028096,0.146295,1559.374328
147,1972-03-01,5.170447,65.046000,61.658226,3783.961641,Spain,-0.013165,-0.020428,1.910477,0.009681,0.060993,0.148207,1622.206362
148,1972-04-01,5.170447,64.553000,59.265099,3858.316264,Spain,-0.007608,-0.005196,1.900577,0.000000,-0.039586,0.138180,1654.082621
149,1972-05-01,5.195862,64.546000,61.188985,4132.586307,Spain,-0.000108,-0.002605,1.895632,0.004903,0.031947,0.156358,1771.663783
150,1972-06-01,5.208062,64.457000,63.042486,4483.603107,Spain,-0.001380,-0.001324,1.893123,0.002345,0.029842,0.169086,1922.146727
151,1972-07-01,5.279223,63.466000,58.432196,4771.557207,Spain,-0.015494,-0.024280,1.847711,0.013571,-0.075942,0.112502,2045.594324
152,1972-08-01,5.333612,63.473000,46.947531,4988.213444,Spain,0.000110,-0.007756,1.833436,0.010250,-0.218836,0.118721,2138.476113
153,1972-09-01,5.408840,63.465000,61.482261,5067.208664,Spain,-0.000126,-0.011754,1.812012,0.014006,0.269718,0.173772,2172.341823
154,1972-10-01,5.445947,63.485000,62.678825,5176.913124,Spain,0.000315,-0.001783,1.808785,0.006837,0.019275,0.169047,2219.372763
155,1972-11-01,5.454588,63.471000,65.013297,5275.668264,Spain,-0.000221,0.000555,1.809790,0.001585,0.036568,0.173340,2261.709666

In [26]:
# Reset
pd.reset_option("display.max_rows")

## Analysis